version: '2'
services:
  octoprint:
    build: .
    image: acrelle/rpi-octoprint
    container_name: octoprint
    ports:
      - 5000:5000
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
     - ~/appdata/octoprint:/home/octoprint/.octoprint
    restart: unless-stopped
